### ISSUE TITLE
Fingerprint Doubt

### ISSUE THREAD

**Issue by mmatheusmmiguel** [mesnico/WifiIndoorLocation#1]
Hey guy,

Can u explain me how can i generate a wifi fingerprint?

Thanks,

**Comment by mesnico** [comment]
Hi @mmatheusmmiguel, sorry for the delayed response.
A wifi fingerprint is a set of access points sensed by the wifi interface in a particular place. Hence, a fingerprint carries the list of sensed access points plus a position information.

For detailed technical informations on how to build a wifi fingerprint, please take a look at this piece of code:
https://github.com/mesnico/WifiIndoorLocation/blob/c122629f0c102df95232f23f404da6354d0a1e41/app/src/main/java/com/unipi/nicola/indoorlocator/fingerprinting/WifiFingerprintingService.java#L146-L198

A ```BroadcastReceiver``` listens for wifi scan completion. When a new wifi scan is ready, the ```onReceive``` method is called. At this point, a list of sensed access points (together with their BSSID and signal strength) is returned and from there a wifi fingerprint can be constructed and saved into the database.

Note that in my implementation I collected ```storeIterations``` scans before building the actual fingerprint, in order to be able to compute an aggregation (by means of ```WifiAPsAggregator```) over multiple scans. This is a simple method to produce a better estimation of the set of sensed access points at the specific location. You can take a look at ```WifiAPsAggregator.java``` to see how I mixed together different access points informations to build a single fingerprint.

Hope it helps

**Comment by mmatheusmmiguel** [comment]
Hi @mesnico 

From what I understand, do you link the fingerprint to a GPS user's location?

**Comment by mesnico** [comment]
@mmatheusmmiguel exactly. Position is acquired during the store phase, initiated by the user by means of the GUI exposed by ```FPStoreFragment```. Using that GUI, user can manually specify position coordinates or activate GPS to retrieve them. Position is then sent from ```FPStoreFragment``` to ``` 	WifiFingerprintingService``` using message passing interfaces. This position is included in the stored fingerprint.

Fingerprint sensed during position estimation phase obviously carries no position information since position is still not known (in fact, it must be generated from the fingerprint matching algorithm)

**Comment by mmatheusmmiguel** [comment]
Hi @mesnico 

And when the person comes close to a fingerprint I retrieve the location tied to that fingerprint in the database?

**Comment by mesnico** [comment]
@mmatheusmmiguel yes, that's the basic idea: take the position associated with the most similar fingerprint in the database (the fingerprint having less distance from the unknown location fingerprint). 

However, in this implementation the idea is a bittle more complicated:

1. I extract from the database all the fingerprints that match the unknown location fingerprint for at least R BSSIDs (R is a parameter defined by the user). This acts like a pre-filtering;
2. Among the retrieved fingerprints I filter out all the ones more distant than a threshold M from the unknown location fingerprint (M again is a parameter);
3. Among the remaining fingerprints I select the first K in order of increasing distance. 
4. I take the centroid between the position coordinates of these last K fingerprints as estimate for the actual position.

Note that the distance function can be defined arbitrarily (I used a modification of the Euclidean distance).
If you have not seen it yet, please take a look at https://github.com/mesnico/WifiIndoorLocation/blob/master/presentation.pdf. Here you can find some interesting details.

Hope it helps!
